mongo-url = "mongodb://nitro:password123@mongo-primary:27017,mongo-secondary:27018/kartoffelMock?replicaSet=rs0"
elasticsearch-urls = ["http://elasticsearch:9200"]
verbose = true

change-stream-namespaces = [
  "kartoffelMock.denormalizedEntity",
  "kartoffelMock.denormalizedDigitalIdentity", 
  "kartoffelMock.denormalizedRole", 
  "kartoffelMock.denormalizedOrganizationGroup"
]

direct-read-namespaces = [
  "kartoffelMock.denormalizedEntity", 
  "kartoffelMock.denormalizedDigitalIdentity", 
  "kartoffelMock.denormalizedRole", 
  "kartoffelMock.denormalizedOrganizationGroup"
]

elasticsearch-retry = true

enable-http-server= true

# workers = ["w1", "w2"]
# cluster-name = "HA"

# replay = true
resume = true

stats= true

[[script]]
namespace = "kartoffelMock.denormalizedEntity"
path = "scripts/transform_entity.js"

# [[script]]
# namespace = "kartoffelMock.denormalizedDigitalIdentity"
# path = "scripts/transform_DI.js"

# [[script]]
# namespace = "kartoffel.denormalizedRole"
# path = "scripts/transform_role.js"

# [script]]
# namespace = "kartoffel.denormalizedOrganizationGroup"
# path = "scripts/transform_group.js"
